'use strict';

/**
 * Shared ^A0 text metrics for every ZPL engine (packing slip, pick list, label).
 *
 * UNIT-AGNOSTIC: estimateWrapLines divides width by font, so it is correct in mm
 * (slip/pick-list engine) or dots (label engine) as long as BOTH arguments use
 * the same unit.
 *
 * This lived inside the layout renderer. It was extracted so the product-label
 * engine could stop using a flat `fontSize * 0.6` guess — the exact constant this
 * glyph model replaced after it proved mis-tuned in BOTH directions
 * (over-reserving mixed-case titles, under-reserving all-caps ones).
 */

// A pathologically long name wraps in full rather than cramming — product names
// are never truncated ("detail is load-bearing to the last word").
const TITLE_MAX_LINES = 6;

// A reserve on the WRAP WIDTH: a title filling more than this fraction of the
// line is predicted to wrap rather than being trusted to fit.
//
// It was 0.90 for six weeks, on the reasoning that "real Zebra ^A0 renders a few
// percent wider than this estimate and than Labelary". Both halves of that were
// wrong, and a printed calibration target (a test sheet of boundary-case lines,
// rendered through Labelary and printed on the real hardware side by side) is
// what showed it:
//
//   · Real Zebra is NOT wider than Labelary. Page 3 — eight real wrapped lines
//     packed to exactly 100.0% of their column — printed matching the Labelary
//     render row for row. The simulator is a faithful width reference.
//   · The error was never a uniform "few percent" that a reserve could absorb.
//     It was a BUCKETED glyph table being wrong per-character, worst on the
//     dash (0.34 scored against 0.903 real) and on the caps a romanized Chinese
//     manufacturer name is made of (N/U/H scored 0.554 against 0.608).
//
// So 0.90 was never slack — it was a blunt instrument covering a table error
// that reached 12% on some strings, and one real line already broke through it.
// The table is now measured per character and re-validated by RENDERING: across
// the review's two proven overruns, the worst caps-heavy manufacturer names in
// the catalogue and the motivating titles, the model's worst error is **+0.05%**
// and its spread is −0.6%..+0.1%.
//
// 0.97 is therefore ~3% of headroom over a sub-1% residual, and the headroom is
// deliberate rather than leftover: it covers what the harness CANNOT see —
// roll-to-roll media tracking, head wear, and any future character that falls
// through to DEFAULT_ADVANCE. Do not tighten it further to buy a line; the
// measurement does not support more than this, and the failure is on paper.
const TITLE_WRAP_SAFETY = 0.97;

// Per-character `^A0` advance in units of the font size, MEASURED — every
// character occurring more than 40 times across 90 days of real order-line
// titles, catalogue product names and manufacturer names. (Regenerated by a
// companion measurement script, not included in this excerpt.)
//
// THIS IS PER-CHARACTER AND NOT BUCKETED, and that is the whole point. The
// first table grouped ("all caps 0.58, most lowercase 0.46"). Real ^A0 caps
// run from J at 0.442 to W at 0.812, so one bucket value is wrong for most of
// its members — and the error is UNBOUNDED on a string that is all of one kind.
// A romanized Chinese manufacturer name is exactly that string: GUANGZHOU /
// SHENZHEN / DONGGUAN are N-U-H-G heavy, and those are the four caps a
// caps-average under-scores hardest.
//
// The first attempt at this calibration measured `ink width / character count`,
// which folds both side bearings into every character and under-scored N/U/H by
// 10% and n/u by 12%. A review caught it by rendering strings the model called
// 97%-full and measuring them at 100%+. The measurement script uses
// repeat-differencing (N vs 2N copies) instead, which cancels the bearings
// exactly. DO NOT re-measure with the naive method; it fails toward
// under-scoring, which is the direction that prints past the box.
//
// Cross-checked at ^A0 fonts 33 and 60 — the advance is a pure ratio, so a
// disagreement between sizes would mean hinting, and there is none.
const GLYPH_ADVANCE = new Map(Object.entries({
  'eo01235"L4687#9°*': 0.480,
  'nupgdEhTFbZq|®': 0.498,
  ',/.(): []\'': 0.295,
  'PBAKXY': 0.553,
  'cyxkvJ': 0.442,
  'HNU&™': 0.608,
  'RDGµ': 0.588,
  // The dash family. It was scored 0.34 in a `ftr()[]{}-/` class for a year, and
  // 63,579 of the characters we print are one of these — it is the single most
  // wrong number the old table held.
  '-%+–—': 0.903,
  'ilj': 0.258,
  'tIf': 0.277,
  'SCV': 0.535,
  's”': 0.423,
  'Mm': 0.757,
  'OQ': 0.572,
  'a': 0.460,
  'r': 0.333,
  'w': 0.663,
  'z': 0.387,
  'W': 0.812,
  '<': 0.995,
}).flatMap(([chs, a]: [string, number]) => [...chs].map((c) => [c, a] as [string, number])));

// An unmeasured character gets a WIDE default, not an average one. Everything we
// actually print is in the table; anything reaching here is a character the
// catalogue has not shown us, and the failure modes are not symmetric —
// over-reserving costs a line of label, under-reserving prints through the QTY
// column. 0.62 sits above every measured letter and below the dash family.
const DEFAULT_ADVANCE = 0.62;

function glyphAdvance(ch) {
  const a = GLYPH_ADVANCE.get(ch);
  return a === undefined ? DEFAULT_ADVANCE : a;
}

function textWidthRatio(s) {
  let t = 0;
  for (const ch of String(s == null ? '' : s)) t += glyphAdvance(ch);
  return t; // width in units of font size
}

// Estimate how many ^FB lines `text` wraps to at `font` inside `width`. The
// renderer caps the ^FB at this SAME count and advances the cursor by it, so an
// accurate estimate means the next field starts exactly below — no gap, no
// overprint. maxLines both caps the return and (via the ^FB) truncates overflow.
// A one-line ^FB does NOT truncate overflow — per the ZPL manual, "text
// exceeding the maximum number of lines overwrites the last line" — so a string
// wider than the block prints its TAIL ON TOP OF ITS HEAD. Wherever a value of
// unbounded length prints into a fixed-width single-line ^FB (the packing-slip
// QTY column, the pick-list qty box), the font must shrink to fit instead:
// qty 200 was rendering as a bold "20" with the last 0 stamped over it, and 1000
// as an unreadable blot — a mis-pick, not a cosmetic defect.
//
// FIT_SAFETY is TITLE_WRAP_SAFETY's cousin and it STAYS AT 0.85 — deliberately,
// even though the two reasons it was originally set low have both now been dealt
// with elsewhere:
//
//  1. "The model under-measures DIGITS." It did — an earlier Labelary
//     calibration put the true digit advance at ~0.49 against a scored 0.46, and
//     that comment said do NOT fix 0.46 because every page count was calibrated
//     against it. The table above now scores digits 0.479, measured, and the
//     page counts were re-derived with it. So this half is fixed AT SOURCE.
//  2. "Real Zebra runs a few % wider than Labelary." It does not — page 3 of the
//     calibration target printed matching the Labelary render row for row. This
//     half was never true.
//
// IT STAYS ANYWAY, AND THAT IS NOT INERTIA. This constant does not guard a
// wrapped paragraph, where being 3% wrong costs a line of paper: it guards a
// SINGLE-LINE ^FB, where being 3% wrong stamps the tail on the head and turns
// qty 200 into "20" — a mis-pick, not a cosmetic defect. And the recorded prod
// failure was not a near miss: the shipped 7.2mm qty font measured
// 3 x 0.46 x 7.2 = 9.94mm against a 10mm gutter — 99.4%, "fits" — and
// overprinted on paper regardless. Whatever ate that last 0.6%, a corrected
// glyph table does not explain it away, and the payoff for tightening here is a
// slightly larger digit rather than a sheet of label. Wrong trade.
//
// Revisit only against a printed qty-column target of its own, never by
// reasoning from the wrap constant.
const FIT_SAFETY = 0.85;

// Largest font (<= `font`) at which `text` fits `width` on one line, floored at
// `minFont`. UNIT-AGNOSTIC: `width`, `font`, `minFont` must share a unit (mm or
// dots) — the test is a ratio. The floor wins over the fit, so a caller that
// sets one is choosing legibility over the overprint guarantee for absurdly long
// values; size it to cover every plausible input (see callers).
//
// `safety` defaults to FIT_SAFETY, which is the packing-slip QTY gutter's number:
// there the block IS the column, its neighbour's ink starts at the block edge,
// and nothing outside it absorbs an error. A caller whose block sits inside a
// PRINTED MARGIN owns a second cushion and passes its own — stacking both
// reserves once cost the widest field on a 1.5in label a quarter of the media.
function shrinkFontToFit(text, width, font, minFont = 0, safety = FIT_SAFETY) {
  const ratio = textWidthRatio(text);
  if (!(ratio > 0) || !(width > 0) || !(font > 0)) return font;
  const fitted = (width * safety) / ratio;
  if (fitted >= font) return font;
  // Clamp the floor to `font`: layout profiles are hand-editable JSON that
  // validateLayout barely checks, so a floor set above the configured size would
  // otherwise make an overlong value print BIGGER than a short one. This only
  // ever shrinks.
  return Math.max(Math.min(minFont, font), fitted);
}

function estimateWrapLines(text, width, font, maxLines = TITLE_MAX_LINES) {
  const s = String(text == null ? '' : text).trim();
  if (!s || !(width > 0) || !(font > 0)) return 1;
  const cap = width / font;              // max line width, in font units
  const spaceW = glyphAdvance(' ');
  let lines = 1;
  let cur = 0;
  for (const word of s.split(/\s+/)) {
    const ww = textWidthRatio(word);
    if (cur === 0) cur = ww;
    else if (cur + spaceW + ww <= cap) cur += spaceW + ww;
    else { lines += 1; cur = ww; }
    // A word wider than a line hard-wraps. This must count the SAME chunks
    // `hardSplitWord` actually cuts, not `ceil(width / cap)`: the renderer breaks
    // on whole CHARACTERS, so every chunk lands at or under `cap` with a
    // remainder of slack, and that slack accumulates. The old arm subtracted
    // `cap` repeatedly — i.e. it assumed a word packs perfectly — and the two
    // then agreed only by coincidence, for the particular glyph widths in force.
    // Re-measuring the glyph table moved those widths and the coincidence broke:
    // at 616 dots / font 33, a 69-character all-caps word reserved 2 lines and
    // rendered 3. The `wrapEquivalence` test caught it, which is what that test
    // is for. Counting the real chunks makes the two agree STRUCTURALLY instead
    // of numerically, so the next table change cannot reopen this.
    // Reaching here with `cur > cap` means `cur === ww` for THIS word — the
    // accumulate branch above is guarded by `<= cap` and cannot overflow.
    if (cur > cap) {
      const chunks = hardSplitWord(word, cap);
      lines += chunks.length - 1;
      cur = textWidthRatio(chunks[chunks.length - 1]);
    }
  }
  return Math.min(maxLines, Math.max(1, lines));
}

// ── Code 128 width ──────────────────────────────────────────────────────────
// The same "prediction must match the render" problem as the text above, for
// bars: `^BC` takes NO ^FB, so ZPL draws the symbol as wide as the data needs
// and NOTHING clips it. A long value simply prints through whatever sits to its
// right — on the warehouse slip that is the TOTAL QTY box, i.e. the number the
// picker counts against.
//
// Width in MODULES = 11 x (start + data symbols + checksum) + 13 (stop bar).
//
// One symbol per CHARACTER. Do NOT model subset C: measured against Labelary at
// 8dpmm, a marketplace's `111-2345678-9012345`-shaped id (19 chars) renders 244
// modules = 11 x (19+2) + 13 exactly, so ^BC's auto mode did not collapse its
// two 7-digit runs into numeric pairs. Assuming it does HALVES the predicted
// width of a numeric id, and under-prediction is the failure mode that lets a
// barcode overprint its neighbour — the expensive direction, same as the
// single-line ^FB above.
function code128Modules(data) {
  const len = String(data == null ? '' : data).length;
  return len ? 11 * (len + 2) + 13 : 0;
}


// ── DataMatrix (ECC200) size ────────────────────────────────────────────────
// Same "prediction must match the render" problem as ^BC above, in two
// dimensions: `^BX` takes no ^FB either, draws a SQUARE of
// `modules x magnification` dots, and clips nothing. Under-predict the module
// count and the symbol prints past its box into the neighbour.
//
// The ECC200 square ladder: [modules per side, ASCII data codewords].
const DATAMATRIX_SQUARES: Array<[number, number]> = [
  [10, 3], [12, 5], [14, 8], [16, 12], [18, 18], [20, 22], [22, 30],
  [24, 36], [26, 44], [32, 62], [36, 86], [40, 114], [44, 144], [48, 174], [52, 204],
];

// ONE CODEWORD PER CHARACTER, which is deliberately PESSIMISTIC. ECC200's ASCII
// encoder packs a pair of CONSECUTIVE DIGITS into a single codeword, so a
// numeric order id really needs about half of this — measured against the real
// ^BX render, an 8-digit marketplace order id lands on 12 modules where this
// model reserves 14, and the 19-char id above on 16 where this reserves 20.
//
// Modelling the pairing would be tighter and is the WRONG trade. The pairing
// only holds while the id stays numeric; an id that gains a letter (or a
// channel that changes its format) silently needs more codewords than the model
// predicted, and that is the direction that prints the symbol past its box —
// the same asymmetry code128Modules is built around. Over-reserving costs one
// magnification step and nothing else, because the symbol is LEFT-ALIGNED in
// its box: a smaller-than-predicted symbol simply leaves extra white to the
// right, which is extra quiet zone, not a defect.
function dataMatrixModules(data) {
  const len = String(data == null ? '' : data).length;
  if (!len) return 0;
  for (const [modules, capacity] of DATAMATRIX_SQUARES) {
    if (capacity >= len) return modules;
  }
  return DATAMATRIX_SQUARES[DATAMATRIX_SQUARES.length - 1][0];
}

// Largest ^BX magnification at which `data` still fits a `box`-dot SQUARE.
// Same shape as fitBarcodeModuleW: `box` and the return share a unit (dots),
// `declared` is a design ceiling, `min` is a last resort rather than a target.
//
// Unlike Code 128 there is no quiet-zone arithmetic here: ECC200 needs only ONE
// module of quiet zone per side (against Code 128's ten), and the box this is
// fitted into is a layout slot with real whitespace around it, so a symbol that
// fills its declared box still clears the requirement.
function fitDataMatrixMagnification(data, box, declared = 5, min = 2) {
  const modules = dataMatrixModules(data);
  const ceiling = Math.max(1, Math.floor(declared || 5));
  if (!modules || !(box > 0)) return ceiling;
  const floor = Math.max(1, Math.min(min, ceiling));
  return Math.max(floor, Math.min(ceiling, Math.floor(box / modules)));
}

// Largest ^BY module width at which `data` still fits `width`. UNIT-AGNOSTIC in
// the same sense as shrinkFontToFit: `width` and the returned module share a
// unit, and ^BY only accepts whole dots, so callers pass dots.
//
// `min` is a last resort, not a target: at 203 dpi a 1-dot module is 0.125mm
// (4.9 mil), which is under what a handheld reliably reads off direct thermal.
// It exists because a hard-to-scan barcode still beats one printed across the
// QTY box, and because the alternative — silently encoding a DIFFERENT id than
// the one printed beside it — is the bug this whole seam exists to prevent.
function fitBarcodeModuleW(data, width, moduleW = 2, min = 1) {
  const modules = code128Modules(data);
  const declared = Math.max(1, Math.floor(moduleW || 2));
  if (!modules || !(width > 0)) return declared;
  const floor = Math.max(1, Math.min(min, declared));
  const fitted = Math.floor(width / modules);
  return Math.max(floor, Math.min(declared, fitted));
}

// ── Taking the line break away from the firmware ────────────────────────────
//
// `estimateWrapLines` answers "how many lines WILL ^FB use". These two answer
// "what lines should WE draw", so the renderer can hand the printer a bare ^FD
// per line and never issue ^FB at all. Why that matters: ^FB left-justified at
// full width is a no-op the firmware waves through, but CENTRED or
// narrow-and-wrapping ^FB makes the printer measure the line before placing the
// first glyph — and that is the path a busy printer silently abandons under a
// burst of jobs.
//
// The measured contrast, on real payloads: a well-known commercial shipping
// app's slip carries 38 ^FB commands and every one of them is `^FB812,100,0,L,0`
// — the full label width, a line cap it can never reach, left-justified — plus
// 31 of its 38 text fields in the BITMAPPED ^AD font, whose glyph widths are a
// table lookup. Ours carried 9, six of them centred, two wrapping at a narrow
// width, every one in the SCALABLE ^A0. Four times the commands, none of the
// work. That is why theirs printed fast and ours went blank at burst depth 5.
//
// wrapTextToLines is a SECOND implementation of the same greedy algorithm, kept
// separate so the RESERVE and the RENDER can be asserted against each other
// rather than sharing a bug. The two agreeing is enforced by test
// (`wrapEquivalence`) — if you edit one, the suite fails until you edit the
// other.

// Break a single word too wide for `cap` into chunks that fit. Never drops a
// character: product names are load-bearing to the last word, so an unbreakable
// token gets carved, not clipped.
function hardSplitWord(word, cap) {
  const out = [];
  let cur = '';
  let curW = 0;
  for (const ch of String(word)) {
    const cw = glyphAdvance(ch);
    if (cur && curW + cw > cap) { out.push(cur); cur = ch; curW = cw; }
    else { cur += ch; curW += cw; }
  }
  if (cur) out.push(cur);
  return out.length ? out : [String(word)];
}

// The actual lines `text` breaks into at `font` within `width`. UNIT-AGNOSTIC
// like the rest of this file (mm or dots, as long as both share one).
//
// Returns EVERY line — there is no maxLines parameter on purpose. Clamping here
// is what ^FB does, and ^FB does not truncate the overflow, it stamps it on top
// of the last line: that is how a long `MAPPED TO: …` catalogue title once
// printed its third line over its second. A caller that must bound the height
// shrinks the FONT until the text fits the line budget (see
// `shrinkFontToFitLines`) instead of dropping words.
function wrapTextToLines(text, width, font) {
  const s = String(text == null ? '' : text).trim();
  if (!s) return [];
  if (!(width > 0) || !(font > 0)) return [s];
  const cap = width / font;
  const spaceW = glyphAdvance(' ');
  const lines = [];
  let cur = '';
  let curW = 0;
  const flush = () => { if (cur) { lines.push(cur); cur = ''; curW = 0; } };
  for (const word of s.split(/\s+/)) {
    if (!word) continue;
    const ww = textWidthRatio(word);
    if (ww > cap) {
      // Mirrors estimateWrapLines' hard-wrap arm, which counts these same chunks.
      flush();
      const chunks = hardSplitWord(word, cap);
      for (let i = 0; i < chunks.length - 1; i++) lines.push(chunks[i]);
      cur = chunks[chunks.length - 1];
      curW = textWidthRatio(cur);
      continue;
    }
    if (!cur) { cur = word; curW = ww; }
    else if (curW + spaceW + ww <= cap) { cur += ` ${word}`; curW += spaceW + ww; }
    else { flush(); cur = word; curW = ww; }
  }
  flush();
  return lines.length ? lines : [s];
}

// Largest font (<= `font`) at which `text` wraps to at most `maxLines` inside
// `width`, floored at `minFont`. The height-bounded cousin of shrinkFontToFit:
// where that one keeps a value on ONE line, this keeps a paragraph inside a
// reserved block. Shrinks the glyph; never removes a word.
function shrinkFontToFitLines(text, width, font, maxLines, minFont = 0) {
  if (!(maxLines > 0) || !(width > 0) || !(font > 0)) return font;
  const floor = Math.max(0, Math.min(minFont, font));
  let f = font;
  // Coarse then fine: 5% steps are plenty — the caller rounds to whole dots.
  while (f > floor && wrapTextToLines(text, width, f).length > maxLines) {
    f = f * 0.95;
    if (f < floor) return floor;
  }
  return f;
}

// Horizontal offset that centres / right-aligns `text` in a `boxW` box, in the
// same unit as boxW and font. This is the arithmetic ZPL will not do without
// ^FB. An early ruling called hand-centring unsafe because the glyph model
// under-measured digits ~9% — but that objection was aimed at ^FB's OVERWRITE
// failure (qty 200 printing as a bold "20"). A bare ^FD cannot overwrite: an
// under-measured string simply sits a few dots off centre, and callers that
// care run shrinkFontToFit FIRST so the string is provably narrower than its
// box before it is placed. Clamped at 0 so a string wider than its box starts
// at the box edge rather than to the left of it.
function alignOffset(text, boxW, font, align) {
  const a = String(align || 'L').toUpperCase();
  if (a !== 'C' && a !== 'R') return 0;
  const tw = textWidthRatio(text) * font;
  const slack = boxW - tw;
  if (!(slack > 0)) return 0;
  return a === 'C' ? slack / 2 : slack;
}

export {
  glyphAdvance, textWidthRatio, estimateWrapLines, shrinkFontToFit,
  wrapTextToLines, shrinkFontToFitLines, alignOffset, hardSplitWord,
  code128Modules, fitBarcodeModuleW,
  dataMatrixModules, fitDataMatrixMagnification,
  TITLE_WRAP_SAFETY, TITLE_MAX_LINES, FIT_SAFETY,
};
